---
name: Should run
author: dafyddj
description: Decide whether the current workflow should run or not
inputs:
  branch-name:
    description:  The branch to check
    default: ${{ github.ref_name }}
  github-token:
    description: GITHUB_TOKEN
    default: ${{ github.token }}
  override:
    description: Workflow runs when this is `true`
    default: ${{ github.event_name == 'pull_request' }}
outputs:
  should-run:
    description: Whether the workflow should run or not
    value: ${{ steps.run-action.outputs.should-run }}
runs:
  using: composite
  steps:
    - id: run-action
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        INPUT_BRANCH_NAME: ${{ inputs.branch-name }}
        INPUT_OVERRIDE: ${{ inputs.override }}
      run: |
        if [[ "${INPUT_OVERRIDE}" = "true" ]]; then
          echo "Forcing run due to override"
          OUTPUT="should-run=true"
          echo "Setting '$OUTPUT'"
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          exit
        fi

        BRANCH_NAME="${INPUT_BRANCH_NAME#refs/heads/}"

        gh_cmd() {
          local GITHUB_REPOSITORY="$1"
          local BRANCH_NAME="$2"

          gh api "repos/${GITHUB_REPOSITORY}/pulls?state=open" \
            | jq --arg branch "$BRANCH_NAME" --arg repo "$GITHUB_REPOSITORY" \
                 '.[] | select(.head.ref == $branch and .head.repo.full_name == $repo) | .number' \
            | wc -l
        }

        echo "Calling: gh_cmd \"$GITHUB_REPOSITORY\" \"$BRANCH_NAME\""
        PR_COUNT=$(gh_cmd "$GITHUB_REPOSITORY" "$BRANCH_NAME")

        if [ $PR_COUNT -gt 0 ]; then
          echo "There is an associated pull request for branch $BRANCH_NAME"
          OUTPUT="should-run=false"
          echo "Setting '$OUTPUT'"
          echo "$OUTPUT" >> $GITHUB_OUTPUT
        else
          echo "There is no associated pull request for branch $BRANCH_NAME"
          OUTPUT="should-run=true"
          echo "Setting '$OUTPUT'"
          echo "$OUTPUT" >> $GITHUB_OUTPUT
        fi
